import { NextResponse } from "next/server";
import { put } from "@vercel/blob";
import { db } from "@/lib/db";
import { sendEmail } from "@/lib/mailer";
import { nextTicketNumber } from "@/lib/tickets";
import { evaluateAndDraft, sendAutoReply } from "@/lib/autoresponder";

// Postmark inbound webhook (spec §4). The ?token= query param is the Inbox's
// inboundToken — it both authenticates the call and selects the brand/inbox,
// so adding a brand is a new Postmark server pointing here with its own token.
//
// Postmark retries on non-2xx and on >10s responses, so this handler is
// idempotent: a payload whose Postmark MessageID we already stored is a no-op.
//
// Known platform limit: Vercel caps request bodies at ~4.5MB, so emails with
// very large attachments can fail at the edge before reaching this code.

export const maxDuration = 60;

type PostmarkHeader = { Name: string; Value: string };
type PostmarkAttachment = {
  Name: string;
  Content: string; // base64
  ContentType: string;
  ContentLength: number;
};
type PostmarkInbound = {
  FromFull?: { Email?: string; Name?: string };
  OriginalRecipient?: string;
  Subject?: string;
  MailboxHash?: string;
  MessageID?: string; // Postmark's internal id (idempotency key)
  TextBody?: string;
  HtmlBody?: string;
  StrippedTextReply?: string;
  Headers?: PostmarkHeader[];
  Attachments?: PostmarkAttachment[];
};

const STATUSES = ["new", "open", "pending", "solved", "closed"];

function header(p: PostmarkInbound, name: string): string | undefined {
  return p.Headers?.find((h) => h.Name.toLowerCase() === name.toLowerCase())?.Value;
}

/** Strip angle brackets/whitespace from an RFC Message-ID for stable matching. */
function normalizeMsgId(id: string | undefined | null): string | null {
  if (!id) return null;
  const trimmed = id.trim().replace(/^<|>$/g, "").trim();
  return trimmed || null;
}

/** True for auto-responders, bounces, and bulk mail we shouldn't page agents for. */
function isAutoGenerated(p: PostmarkInbound): boolean {
  const auto = header(p, "Auto-Submitted");
  if (auto && auto.toLowerCase() !== "no") return true;
  const precedence = header(p, "Precedence")?.toLowerCase();
  if (precedence && ["bulk", "junk", "auto_reply", "list"].includes(precedence)) return true;
  if (header(p, "X-Autoreply") || header(p, "X-Autorespond")) return true;
  const failedRecipients = header(p, "X-Failed-Recipients");
  if (failedRecipients) return true;
  return false;
}

export async function POST(req: Request) {
  const token = new URL(req.url).searchParams.get("token");
  if (!token) return NextResponse.json({ error: "Missing token." }, { status: 401 });

  const inbox = await db.inbox.findUnique({
    where: { inboundToken: token },
    include: {
      board: {
        include: {
          columns: true,
          fields: { include: { options: true } },
        },
      },
    },
  });
  if (!inbox) return NextResponse.json({ error: "Unknown inbox token." }, { status: 401 });

  const p: PostmarkInbound = await req.json();
  const fromEmail = p.FromFull?.Email?.trim().toLowerCase();
  const fromName = p.FromFull?.Name?.trim() || null;

  // Nothing actionable, or mail from our own support address (loop guard).
  if (!fromEmail) return NextResponse.json({ ok: true, skipped: "no sender" });
  if (fromEmail === inbox.supportEmail.toLowerCase()) {
    return NextResponse.json({ ok: true, skipped: "own address" });
  }

  // Idempotency: Postmark retried a payload we already processed.
  if (p.MessageID) {
    const dupe = await db.message.findFirst({
      where: { providerMessageId: p.MessageID, ticket: { inboxId: inbox.id } },
      select: { id: true, ticketId: true },
    });
    if (dupe) return NextResponse.json({ ok: true, ticketId: dupe.ticketId, duplicate: true });
  }

  const isAuto = isAutoGenerated(p);
  const isAmazon =
    fromEmail.endsWith("marketplace.amazon.com") || fromEmail.endsWith("marketplace.amazon.ca");
  const channel = isAmazon ? "amazon" : "email";

  // ---- Route to a ticket (spec §4 priority order) ----
  let ticket =
    // a) tokenized Reply-To: hash+<replyToken>@inbound…
    (p.MailboxHash
      ? await db.ticket.findFirst({ where: { replyToken: p.MailboxHash, inboxId: inbox.id } })
      : null) ??
    null;

  // b) In-Reply-To / References → a Message we've stored
  if (!ticket) {
    const refs = [
      normalizeMsgId(header(p, "In-Reply-To")),
      ...(header(p, "References")?.split(/\s+/).map(normalizeMsgId) ?? []),
    ].filter((r): r is string => !!r);
    if (refs.length) {
      const match = await db.message.findFirst({
        where: { messageIdHeader: { in: refs }, ticket: { inboxId: inbox.id } },
        orderBy: { createdAt: "desc" },
        select: { ticketId: true },
      });
      if (match) ticket = await db.ticket.findUnique({ where: { id: match.ticketId } });
    }
  }

  // c) open ticket from the same sender in the last 7 days
  if (!ticket) {
    ticket = await db.ticket.findFirst({
      where: {
        inboxId: inbox.id,
        customerEmail: fromEmail,
        status: { notIn: ["closed"] },
        updatedAt: { gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
      },
      orderBy: { updatedAt: "desc" },
    });
  }

  // d) create a new ticket (+ Customer upsert; Amazon relays get no Customer row)
  const columns = inbox.board.columns.sort((a, b) => a.position - b.position);
  const colByStatus = (s: string) =>
    columns.find((c) => c.name.trim().toLowerCase() === s) ?? columns[0];
  let created = false;

  if (!ticket) {
    created = true;
    let customerId: string | null = null;
    if (!isAmazon) {
      const customer = await db.customer.upsert({
        where: { email: fromEmail },
        create: { email: fromEmail, name: fromName },
        update: fromName ? { name: fromName } : {},
      });
      customerId = customer.id;
    }
    const newCol = colByStatus("new");
    const last = await db.ticket.findFirst({
      where: { columnId: newCol.id },
      orderBy: { position: "desc" },
    });
    const number = await nextTicketNumber(inbox.id);
    ticket = await db.ticket.create({
      data: {
        number,
        inboxId: inbox.id,
        boardId: inbox.boardId,
        columnId: newCol.id,
        subject: p.Subject?.trim() || "(no subject)",
        position: (last?.position ?? 0) + 1,
        channel,
        status: STATUSES.includes(newCol.name.trim().toLowerCase())
          ? newCol.name.trim().toLowerCase()
          : "new",
        customerId,
        customerEmail: fromEmail,
        customerName: fromName,
        amazonRelayAddr: isAmazon ? p.FromFull?.Email ?? null : null,
      },
    });

    // Tag chips so the board filters work from day one.
    const setChip = async (fieldName: string, optionLabel: string) => {
      const field = inbox.board.fields.find((f) => f.name === fieldName);
      const opt = field?.options.find((o) => o.label.toLowerCase() === optionLabel.toLowerCase());
      if (field && opt) {
        await db.ticketFieldValue.upsert({
          where: { ticketId_fieldId: { ticketId: ticket!.id, fieldId: field.id } },
          create: { ticketId: ticket!.id, fieldId: field.id, optionId: opt.id },
          update: { optionId: opt.id },
        });
      }
    };
    await setChip("Channel", isAmazon ? "Amazon" : "Email");
    // Auto-responders/bounces: park at low priority instead of paging anyone.
    if (isAuto) await setChip("Priority", "Low");
  }

  // ---- Store the message ----
  const message = await db.message.create({
    data: {
      ticketId: ticket.id,
      direction: "inbound",
      fromAddr: p.FromFull?.Email ?? fromEmail,
      toAddr: p.OriginalRecipient || inbox.supportEmail,
      subject: p.Subject ?? null,
      bodyText: p.StrippedTextReply?.trim() || p.TextBody || null,
      bodyHtml: p.HtmlBody || null,
      messageIdHeader: normalizeMsgId(header(p, "Message-ID")),
      inReplyTo: normalizeMsgId(header(p, "In-Reply-To")),
      references: header(p, "References") ?? null,
      provider: "postmark",
      providerMessageId: p.MessageID ?? null,
    },
  });

  // Attachments → Vercel Blob (skip zero-byte/inline-cid noise is fine to keep simple).
  const attachmentErrors: string[] = [];
  for (const att of p.Attachments ?? []) {
    if (!att?.Content || !att.Name) continue;
    try {
      const blob = await put(
        `tickets/${ticket.id}/${message.id}/${att.Name}`,
        Buffer.from(att.Content, "base64"),
        { access: "public", contentType: att.ContentType || "application/octet-stream" }
      );
      await db.attachment.create({
        data: {
          messageId: message.id,
          filename: att.Name,
          contentType: att.ContentType || "application/octet-stream",
          blobUrl: blob.url,
          sizeBytes: att.ContentLength ?? null,
        },
      });
    } catch (err) {
      console.error(`[inbound] attachment upload failed: ${att.Name}`, err);
      attachmentErrors.push(att.Name);
    }
  }

  // ---- Status transition (spec §4 step 5) ----
  // New tickets stay in New; replies on existing tickets go to Open (incl.
  // reopening solved/closed ones).
  const data: Record<string, unknown> = { lastMessageAt: new Date() };
  if (!created && ["pending", "solved", "closed"].includes(ticket.status)) {
    const openCol = colByStatus("open");
    data.columnId = openCol.id;
    data.status = "open";
  }
  const updated = await db.ticket.update({ where: { id: ticket.id }, data });

  // ---- Notify the assignee (in-app agents only — never the customer) ----
  if (!created && !isAuto && updated.assigneeId) {
    const assignee = await db.user.findUnique({ where: { id: updated.assigneeId } });
    if (assignee) {
      await sendEmail({
        to: assignee.email,
        subject: `New reply on: ${updated.subject}`,
        html: `<p>${fromName ?? fromEmail} replied on <b>${updated.subject}</b>.</p>
               <p><a href="${process.env.APP_URL ?? ""}/boards/${updated.boardId}?ticket=${updated.id}">Open ticket</a></p>`,
      });
    }
  }

  // ---- AI first-response acknowledgment ----
  // Fires only on a NEW ticket from a real customer (not auto/bounce, not
  // Amazon relay), and only when the inbox autoresponder is switched to "live".
  // The lib does its own junk filtering; failures never break ticketing.
  let autoReplied = false;
  if (created && !isAuto && !isAmazon && inbox.autoresponderMode === "live") {
    try {
      const decision = await evaluateAndDraft({
        fromName,
        fromEmail,
        subject: p.Subject ?? "",
        bodyText: message.bodyText ?? "",
      });
      if (decision.respond && decision.reply) {
        const sentId = await sendAutoReply({
          inbox,
          ticketId: ticket.id,
          ticketSubject: ticket.subject,
          customerEmail: fromEmail,
          inboundMessageIdHeader: message.messageIdHeader,
          replyText: decision.reply,
        });
        autoReplied = !!sentId;
      }
    } catch (err) {
      console.error("[inbound] autoresponder failed", err);
    }
  }

  return NextResponse.json({
    ok: true,
    ticketId: ticket.id,
    messageId: message.id,
    created,
    autoReplied,
    ...(attachmentErrors.length ? { attachmentErrors } : {}),
  });
}
